version: '3.3'

services:
   db:
     image: mariadb:latest
     volumes:
       - MusUS-db:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: musUSR00t
       MYSQL_DATABASE: musus
       MYSQL_USER: MusUS
       MYSQL_PASSWORD: musUSUs3r

   musus:
     build:
      context: ./MusUS
      dockerfile: Dockerfile
     depends_on:
       - db
     image: musus:latest
     ports:
       - "80:80"
     restart: always
     environment:
       MUSUS_DB_HOST: db
       MUSUS_DB_USER: MusUS
       MUSUS_DB_PASSWORD: musUSUs3r
       MUSUS_DB_NAME: musus
volumes:
    MusUS-db: {}